package com.luo.flink.entity.business;

import lombok.Builder;
import lombok.Data;

import java.sql.Timestamp;
import java.util.Calendar;

@Data
@Builder
public class CJCJTBJD {

    private String king;
    private String zzid;
    private String reportid;
    private String bh;
    private String dwxtm;
    private String dwmc;
    private String bgq;
    private String yhid;
    private Timestamp tbkssj;
    private Timestamp tbjzsj;
    private Timestamp txkssj;
    private Timestamp cbjzsj;
    private Timestamp tbsj;
    private String zzjgdm;
    private String gljg;
    private String sjztbm;
    private String sjddfsdm;
    private String ycbz;
    private String tjjgjbdm;
    private String tjjgjbmc;
    private String ysh;
    private String bbbz;
    private String xmid;
    private String zgysr;
    private Timestamp zgyssj;
    private String xmmc;
    private String zgyszt;
    private Timestamp qyckjzsj;
    private String xyfstzbz;
    private String sffstzbz;
    private String bxyfstzyy;
    private String bbdjbz;
    private String tzsbh;
    private String rwid;
    private String cjzggzzid;
    private String qyzzbbzt;
    private String qyzzshzt;
    private String dqshzt;
    private Timestamp qyzztjsj;
    private String syshzt;
    private String xtshr;
    private Timestamp xtshsj;
    private String tbrmc;
    private String xtshrmc;
    private String zgysrmc;
    private String tzstjjg;
    private String sfqmtj;
    private String bfkzbz;
    private Timestamp inserttime;
    private String commitflag;
    private String qytbr;
    private Timestamp committime;
    private String qyyhid;
    private String jgysrTjjb01;
    private String jgysrmcTjjb01;
    private Timestamp jgyssjTjjb01;
    private String jgysztTjjb01;
    private String jgsyshztTjjb01;
    private Timestamp jgsyshsjTjjb01;
    private String jgysrTjjb02;
    private String jgysrmcTjjb02;
    private Timestamp jgyssjTjjb02;
    private String jgysztTjjb02;
    private String jgsyshztTjjb02;
    private Timestamp jgsyshsjTjjb02;
    private String jgysrTjjb03;
    private String jgysrmcTjjb03;
    private Timestamp jgyssjTjjb03;
    private String jgysztTjjb03;
    private String jgsyshztTjjb03;
    private Timestamp jgsyshsjTjjb03;
    private String jgysrTjjb04;
    private String jgysrmcTjjb04;
    private Timestamp jgyssjTjjb04;
    private String jgysztTjjb04;
    private String jgsyshztTjjb04;
    private Timestamp jgsyshsjTjjb04;
    private String jgysrTjjb05;
    private String jgysrmcTjjb05;
    private Timestamp jgyssjTjjb05;
    private String jgysztTjjb05;
    private String jgsyshztTjjb05;
    private Timestamp jgsyshsjTjjb05;
    private String jgysrTjjb06;
    private String jgysrmcTjjb06;
    private Timestamp jgyssjTjjb06;
    private String jgysztTjjb06;
    private String jgsyshztTjjb06;
    private Timestamp jgsyshsjTjjb06;
    private String clientip;
    private String backTjjgjbdm;
    private Timestamp backSbjzsj;
    private String backFlag;
    private Timestamp firstTjsj;
    private String wlryydm;
    private String wlryysm;
    private String sbTjjgdm;
    private String sbTjjgjbdm;
    private String tjzydm;
    private String jgysyjTjjb01;
    private String jgysyjTjjb02;
    private String jgysyjTjjb03;
    private String jgysyjTjjb04;
    private String jgysyjTjjb05;
    private String jgysyjTjjb06;
    private String gsfrdm;
    private Timestamp xqtbkssj;
    private Timestamp jgyskssjTjjb01;
    private Timestamp jgyskssjTjjb02;
    private Timestamp jgyskssjTjjb03;
    private Timestamp jgyskssjTjjb04;
    private Timestamp jgyskssjTjjb05;
    private Timestamp jgyskssjTjjb06;


    public TFillTask getTask() {
        Calendar instance = Calendar.getInstance();
        TFillTask tFillTask = new TFillTask();
        tFillTask.setAreaCode(gljg.substring(0, 6));
        tFillTask.setBh(bh);
        tFillTask.setBgqb(bgq.substring(bgq.length() - 2));
        tFillTask.setBgq(bgq.substring(0, 6));
        tFillTask.setDwxtm(dwxtm);
//        tFillTask.setOrgname();
//        tFillTask.setTbjzrq();
//        tFillTask.setSbqk();
//        tFillTask.setSbsj();
        tFillTask.setCreateTime(new Timestamp(instance.getTimeInMillis()));
        tFillTask.setUpdateTime(new Timestamp(instance.getTimeInMillis()));
        tFillTask.setZzid(zzid);
        return tFillTask;
    }
}
