package com.luo.flink.entity.business;


import lombok.Builder;
import lombok.Data;

import java.sql.Blob;
import java.sql.Clob;
import java.sql.Timestamp;

@Builder
@Data
public class GHBBBBZC {

    private String reportid;
    private String bh;
    private String dcfffldm;
    private String bbzwqc;
    private String bbywqc;
    private String bbzwjc;
    private String bb;
    private String bblx;
    private String zyfldm;
    private String zgzy;
    private String tbsm;
    private String wh;
    private String dcnr;
    private String dcpddm;
    private String dcpdms;
    private Timestamp qysj;
    private Timestamp tysj;
    private Timestamp yxqz;
    private Float bbsx;
    private Float txsj;
    private String txsjms;
    private String bbztdm;
    private String bbjb;
    private String spr;
    private String spjg;
    private String pzhjg;
    private String pzwh;
    private String bajg;
    private String bawh;
    private String zbjg;
    private String gljg;
    private String gljgfzr;
    private String wlbmc;
    private String bz;
    private String bzh;
    private String cjr;
    private Timestamp cjsj;
    private String xgr;
    private Timestamp xgsj;
    private Timestamp tjspsj;
    private String sfyxjzlssj;
    private String bbbgsm;
    private String qzbh;
    private String sybbid;
    private String sqbid;
    private String tqbh;
    private String lsbz;
    private String tjdcdxjblxdm;
    private String dclylx;
    private Blob zbs;
    private Clob bywj;
    private String bdcml;
    private Blob hzgxyj;
    private Blob hzbsjys;
    private Blob bbqjbl;
    private String ms;
    private String spyj;
    private String bfgbbid;
    private String scbz;
    private String sfkwhtbfw;
    private Integer hzsjls;
    private String gzbbbm;
    private String gzmlbm;
    private Timestamp sjylx;
    private String cjbm;
    private Timestamp bbcjsj;
    private String xdr;
    private Timestamp xdsj;
    private String xdsm;
    private String bbsm;
    private String tbfw;
    private String bbqbdm;
    private String ssrw;
    private String tbsjsm;
    private String bbsyhy;
    private String hzsyjgdm;
    private Blob sjbs;
    private Blob bydx;
    private String qsfs;
    private Blob htmlby;
    private Blob excelby;
    private String nbbs;
    private Integer hzblx;
    private String sjcjfs;
    private String bbfl;
    private String hzbsjbb;
    private String bbzldm;
    private String dcdxlxdm;
    private String tbdyfw;
    private String tbhyfw;
    private String dcdwsl;
    private String bsdw;
    private String bsdwlxdm;
    private String bsfsdm;
    private String reReportid;
    private String sftb;
    private String tjzydm;
    private String sfglb;
    private String sffrb;
    private String hasSqTq;
    private String setRowBgcolor;
    private Clob blockjson;
    private String tblx;
    private String yw01;
    private String yw02;
    private String yw03;
    private String yw04;
    private String yw05;
    private String yw06;
    private String yw07;
    private String yw08;
    private String yw09;
    private String yw10;
}
